name: C/C++ CI

on: [push]

jobs:
  # build:

  #   runs-on: ubuntu-latest

  #   steps:
  #   - uses: actions/checkout@master

  #   - name: compile labo01
  #     run: make labo01

  #   - name: run labo01
  #     run: ./bin/labo01  < tests/inputs/inputs1.txt


  # cmake:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@master

  #   - name: run cmake
  #     run: make cmake

  #   - name: run labo01 with inputs1
  #     run: ./bin/labo01 < tests/inputs/inputs1.txt

  #   - name: run labo01 with inputs2
  #     run: ./bin/labo01 < tests/inputs/inputs2.txt

  # tests:

  #   runs-on: ubuntu-latest

  #   steps:
  #   - uses: actions/checkout@master

  #   - name: compile tests
  #     run: make compile_tests

  #   - name: test test_point_get
  #     run: ./bin/test_point_get

  #   - name: test test_point_set
  #     run: ./bin/test_point_set