name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: compile labo01
      run: make labo01

    - name: run labo01
      run: ./labo01


  # cmake:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@master

  #   - name: run cmake
  #     run: make cmake

  #   - name: run labo01 with inputs1
  #     run: ./bin/labo01 < tests/inputs/inputs1.txt

  #   - name: run labo01 with inputs2
  #     run: ./bin/labo01 < tests/inputs/inputs2.txt

  tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: compile tests
      run: make compile_tests

    - name: test test_circle
      run: ./bin/test_circle
      
    - name: test test_triangle
      run: ./bin/test_triangle
